### ISSUE TITLE
Is it possible to create keys in the browser?

### ISSUE THREAD

**Issue by philholden** [ssbc/ssb-keys#24]
I am getting this error

``` bash
ERROR in ./~/ssb-keys/eccjs.js
Module not found: Error: Cannot resolve module 'eccjs' in /Users/ph185068/personal/songs/swarmlog/song-db/node_modules/ssb-keys
 @ ./~/ssb-keys/eccjs.js 3:10-26

ERROR in ./~/mkdirp/index.js
Module build failed: Error: unsupported type for static module: LogicalExpression
at expression:

 opts.fs || fs

    at traverse (/Users/ph185068/personal/songs/swarmlog/song-db/node_modules/static-module/index.js:301:34)
    at walk (/Users/ph185068/personal/songs/swarmlog/song-db/node_modules/static-module/index.js:224:18)
    at walk (/Users/ph185068/personal/songs/swarmlog/song-db/node_modules/falafel/index.js:49:9)
    at /Users/ph185068/personal/songs/swarmlog/song-db/node_modules/falafel/index.js:46:17
    at forEach (/Users/ph185068/personal/songs/swarmlog/song-db/node_modules/foreach/index.js:12:16)
    at walk (/Users/ph185068/personal/songs/swarmlog/song-db/node_modules/falafel/index.js:34:9)
    at /Users/ph185068/personal/songs/swarmlog/song-db/node_modules/falafel/index.js:46:17
    at forEach (/Users/ph185068/personal/songs/swarmlog/song-db/node_modules/foreach/index.js:12:16)
    at walk (/Users/ph185068/personal/songs/swarmlog/song-db/node_modules/falafel/index.js:34:9)
    at /Users/ph185068/personal/songs/swarmlog/song-db/node_modules/falafel/index.js:41:25
 @ ./~/ssb-keys/index.js 2:17-34
```

Is there a way I can create keys in browser just using `eccjs`?

**Comment by emilbayes** [comment]
`k256` keys are now deprecated, so this can be closed :)

**Comment by dominictarr** [comment]
yup, and for the record, this will create keys and store them in localstorage
